### ISSUE TITLE
Installation Failed!

### ISSUE THREAD

**Issue by abser** [kitconcept/robotframework-react#5]
I installed all librarires mentioned in requirements.txt but `pip2 install robotframework-react` give me below output

_Could not find a version that satisfies the requirement robotframework-react (from versions: )
No matching distribution found for robotframework-react_

**Comment by tisto** [comment]
@abser there is no release of robotframework-react yet. I am afraid you have to download and install the package manually for now.

**Comment by ianlg** [comment]
pardon my ignorance but how do I install react library manually for robot framework?

**Comment by tisto** [comment]
@ianig clone the repo and run "python setup.py install" within the robotframework-react directory. Make sure you use the same "python" interpreter that you use for running your robot tests.

I will try to do a first alpha release in the next days...

**Comment by jward-magento** [comment]
Any updates on this project?

**Comment by tisto** [comment]
robotframework-react 1.0.0a1 has been released: https://pypi.python.org/pypi/robotframework-react/1.0.0a1
